name: Docker Image chess

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./images/ -t gowshik79/my_app:latest
    - name: push images
      run: 
        docker push  gowshik79/my_app:latest
